// <auto-generated />
namespace Recruitment_System_Management1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditRole : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditRole));
        
        string IMigrationMetadata.Id
        {
            get { return "202105070244291_EditRole"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
